version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 18
    commands:
      - echo Installing dependencies

  build:
    commands:
      - echo Building frontend...
      - cd frontend
      - npm install
      - npm run build
      - cd ..
      - echo Building backend...
      - cd backend
      - ./mvnw clean package -DskipTests
      - cd ..

  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - backend/target/*.jar
    - frontend/dist/**/*
  discard-paths: no
